version: 2
updates:
- package-ecosystem: maven
  directory: /
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: master
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
